//! Kubelet device plugin for the rusteron DPDK ENA transport (plan §10.3).
//!
//! Loads the pair inventory written by `deploy/aws-eks/node/
//! bootstrap-dpdk-ena.sh`, serves the kubelet v1beta1 Registration and
//! DevicePlugin services on a unix socket under /var/lib/kubelet/device-plugins/,
//! and keeps re-registering while the kubelet is up (including after kubelet
//! restarts, when its socket reappears). The plugin exits nonzero rather than
//! register an unsafe inventory.

mod inventory;
mod service;

use crate::inventory::Inventory;
use crate::service::{sysfs_health, DevicePluginService, RegistrationService, SysfsRoots};
use hyper_util::rt::TokioIo;
use std::error::Error;
use std::path::PathBuf;
use std::time::Duration;
use tokio::net::UnixListener;
use tokio_stream::wrappers::UnixListenerStream;
use tonic::transport::{Endpoint, Server};
use tonic::Request;
use tower::service_fn;

// Generated by build.rs (protox -> tonic-prost-build): package `v1beta1`
// lands as top-level items in OUT_DIR/v1beta1.rs.
include!(concat!(env!("OUT_DIR"), "/v1beta1.rs"));

const RESOURCE_NAME: &str = "rusteron.io/dpdk-ena-pair";
const API_VERSION: &str = "v1beta1";

fn env_or(name: &str, default: &str) -> String {
    std::env::var(name).unwrap_or_else(|_| default.to_string())
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    env_logger::Builder::from_env(env_logger::Env::default().default_filter_or("info")).init();

    let inventory_path = PathBuf::from(env_or(
        "RUSTERON_DPDK_INVENTORY",
        "/var/lib/rusteron-dpdk/ena-pairs.json",
    ));
    let kubelet_dir = PathBuf::from(env_or("RUSTERON_KUBELET_DIR", "/var/lib/kubelet/device-plugins"));
    let endpoint = env_or("RUSTERON_DPDK_ENDPOINT", "rusteron-dpdk.sock");
    let poll_interval = Duration::from_millis(env_or("RUSTERON_DPDK_POLL_INTERVAL_MS", "5000").parse().unwrap_or(5000));
    let roots = SysfsRoots {
        sys_root: PathBuf::from(env_or("RUSTERON_DPDK_SYSFS_ROOT", "/sys")),
        vfio_root: PathBuf::from(env_or("RUSTERON_DPDK_VFIO_ROOT", "/dev/vfio")),
    };

    // Reject duplicate/unsafe inventories before registering (plan §10.3).
    let inventory = Inventory::load(&inventory_path)
        .map_err(|e| format!("refusing to start with {e}; run node/bootstrap-dpdk-ena.sh"))?;
    log::info!(
        "loaded {} ENA pair(s) from {}",
        inventory.pairs.len(),
        inventory_path.display()
    );

    let socket_path = kubelet_dir.join(&endpoint);
    if socket_path.exists() {
        std::fs::remove_file(&socket_path)
            .map_err(|e| format!("cannot remove stale socket {}: {e}", socket_path.display()))?;
    }
    let listener = UnixListener::bind(&socket_path)
        .map_err(|e| format!("cannot bind plugin socket {}: {e}", socket_path.display()))?;
    log::info!("serving device plugin on {}", socket_path.display());

    let register_task = tokio::spawn(register_loop(
        kubelet_dir.join("kubelet.sock"),
        RegisterRequest {
            version: API_VERSION.to_string(),
            endpoint,
            resource_name: RESOURCE_NAME.to_string(),
            options: Some(DevicePluginOptions {
                pre_start_required: false,
                get_preferred_allocation_available: false,
            }),
        },
    ));

    Server::builder()
        .add_service(registration_server::RegistrationServer::new(RegistrationService))
        .add_service(device_plugin_server::DevicePluginServer::new(DevicePluginService::new(
            inventory,
            roots,
            sysfs_health,
            poll_interval,
        )))
        .serve_with_incoming_shutdown(UnixListenerStream::new(listener), shutdown_signal())
        .await?;

    register_task.abort();
    Ok(())
}

async fn shutdown_signal() {
    let _ = tokio::signal::ctrl_c().await;
}

/// Register with the kubelet, re-registering after kubelet restarts (its
/// socket disappears and reappears). Idempotent: while the socket is present
/// we stay registered.
async fn register_loop(kubelet_sock: PathBuf, request: RegisterRequest) {
    let mut backoff = Duration::from_secs(1);
    let mut registered = false;
    loop {
        if kubelet_sock.exists() {
            if !registered {
                match register(&kubelet_sock, &request).await {
                    Ok(()) => {
                        log::info!("registered {RESOURCE_NAME} with kubelet");
                        registered = true;
                    }
                    Err(e) => log::warn!("kubelet registration failed: {e}"),
                }
            }
        } else {
            // Kubelet restarting or not yet up.
            registered = false;
        }
        tokio::time::sleep(backoff).await;
        backoff = (backoff * 2).min(Duration::from_secs(30));
    }
}

async fn register(kubelet_sock: &std::path::Path, request: &RegisterRequest) -> Result<(), Box<dyn Error>> {
    let sock = kubelet_sock.to_path_buf();
    let channel = Endpoint::from_static("http://[::]")
        .connect_with_connector(service_fn(move |_| {
            let sock = sock.clone();
            async move {
                let stream = tokio::net::UnixStream::connect(sock).await?;
                Ok::<_, std::io::Error>(TokioIo::new(stream))
            }
        }))
        .await?;
    registration_client::RegistrationClient::new(channel)
        .register(Request::new(request.clone()))
        .await?;
    Ok(())
}
