/* automatically generated by rust-bindgen 0.72.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct aeron_header_stct {
    pub frame: *mut aeron_data_header_t,
    pub initial_term_id: i32,
    pub position_bits_to_shift: usize,
    pub fragmented_frame_length: i32,
    pub context: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of aeron_header_stct"][::std::mem::size_of::<aeron_header_stct>() - 40usize];
    ["Alignment of aeron_header_stct"][::std::mem::align_of::<aeron_header_stct>() - 8usize];
    ["Offset of field: aeron_header_stct::frame"][::std::mem::offset_of!(aeron_header_stct, frame) - 0usize];
    ["Offset of field: aeron_header_stct::initial_term_id"]
        [::std::mem::offset_of!(aeron_header_stct, initial_term_id) - 8usize];
    ["Offset of field: aeron_header_stct::position_bits_to_shift"]
        [::std::mem::offset_of!(aeron_header_stct, position_bits_to_shift) - 16usize];
    ["Offset of field: aeron_header_stct::fragmented_frame_length"]
        [::std::mem::offset_of!(aeron_header_stct, fragmented_frame_length) - 24usize];
    ["Offset of field: aeron_header_stct::context"][::std::mem::offset_of!(aeron_header_stct, context) - 32usize];
};
